#!/bin/sh

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
[ -d "$cachedir" ] || mkdir "$cachedir"
cache=$cachedir/dmenu_cache
historyfile=$cachedir/dmenu_history

IFS=:
stest -dqr -n "$cache" $PATH && stest -flx $PATH | sort -u > "$cache"
unset IFS

awk -v histfile=$historyfile '
BEGIN {
        while( (getline < histfile) > 0 ) {
                sub("^[0-9]+\t","")
                print
                x[$0]=1
        }
} !x[$0]++ ' "$cache" | dmenu "$@" | awk -v histfile=$historyfile '
BEGIN {
        FS=OFS="\t"
        while( (getline < histfile) > 0 ) {
                count=$1
                sub("^[0-9]+\t","")
                fname=$0
                history[fname]=count
        }
        close(histfile)
}

{
        history[$0]++
        print
}

END {
        if(!NR) exit
        for (f in history)
                print history[f],f | "sort -t '\t' -k1rn >" histfile
}
' | while read cmd; do ${SHELL:-"/bin/sh"} -c "$cmd" & done
